# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVS8srH6RhudkS62aq5HWqeZ1W1SuGBH
"""

import pandas as pd
import numpy as np

def clean_data(df):
    # Display the initial state of the DataFrame
    print("Initial DataFrame:")
    print(df)
    print()

    # Handle missing values by filling them with appropriate values or dropping them
    df.fillna(method='ffill', inplace=True)  # Forward fill missing values
    df.dropna(inplace=True)  # Drop rows with any remaining missing values

    # Handle duplicates by dropping them
    df.drop_duplicates(inplace=True)

    # Convert incorrect data types
    # Example: Convert string columns to numeric if possible
    numeric_columns = df.select_dtypes(include=[np.number]).columns
    df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

    # Display the cleaned DataFrame
    print("Cleaned DataFrame:")
    print(df)
    print()

# Get the file path from the user
file_path = input("Enter the file path for the CSV file: ")
print(" File has opened successfully")

# Read the data from the provided file path
data = pd.read_csv(file_path)

# Create DataFrame from the data
df = pd.DataFrame(data)

# Clean the data
clean_data(df)